/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_audioan_audioan_jni_NativeAudio */

#ifndef _Included_com_audioan_audioan_jni_NativeAudio
#define _Included_com_audioan_audioan_jni_NativeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_audioan_audioan_jni_NativeAudio
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_audioan_audioan_jni_NativeAudio_createEngine
        (JNIEnv *, jclass);

/*
 * Class:     com_audioan_audioan_jni_NativeAudio
 * Method:    createBufferQueueAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_audioan_audioan_jni_NativeAudio_createBufferQueueAudioPlayer
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_audioan_audioan_jni_NativeAudio
 * Method:    write
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_audioan_audioan_jni_NativeAudio_write
        (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_audioan_audioan_jni_NativeAudio
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_audioan_audioan_jni_NativeAudio_play
        (JNIEnv *, jclass);

/*
 * Class:     com_audioan_audioan_jni_NativeAudio
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_audioan_audioan_jni_NativeAudio_stop
        (JNIEnv *, jclass);

/*
 * Class:     com_audioan_audioan_jni_NativeAudio
 * Method:    getBufferPadding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_audioan_audioan_jni_NativeAudio_getBufferPadding
        (JNIEnv *, jclass);

/*
 * Class:     com_audioan_audioan_jni_NativeAudio
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_audioan_audioan_jni_NativeAudio_shutdown
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
